class MyAssets {
  static const String bg = "assets/bg.jpg";
  static const String logo = "assets/logo.png";
  static const String floor = "assets/floor.png";
  static const String zone = "assets/zone.png";
  static const String preset = "assets/preset.png";
  static const String delete = "assets/delete.png";
  static const String edit = "assets/edit.png";
  static const String home = "assets/home.png";
  static const String use = "assets/use.png";
  static const String save = "assets/save.png";
  static const String volumn_on = "assets/volumn_on.png";
  static const String volume_active = "assets/volume_active2.png";
  static const String volume_normal3= "assets/volume_fix2.png";
  static const String volume_normal2 = "assets/volume_fix.png";
  static const String volume_normal = "assets/volume_normal2.png";
  static const String volumn_off = "assets/volumn_off.png";
  static const String volumn_up = "assets/volume_up.png";
  static const String bg1 = "assets/bg1.png";
  static const String bg2 = "assets/bg2.png";
  static const String bg3 = "assets/bg3.png";
  static const String bg4 = "assets/bg4.png";
  static const String map = "assets/map.png";
  static const String map_volume = "assets/map_volume.png";
  static const String volume = "assets/volume.png";
  static const String bookmark = "assets/bookmark.png";
  static const String gear = "assets/gear.png";
  static const String support = "assets/support.png";
}
